### PR TITLE
Session1 Scripts and Files

### PR DESCRIPTION
**Pull request by hila3000**
Added the actual exercise1/2 scripts I wrote for this session.
Also added ppl_ages.json file which is the input file I used for exercise1.

### CODE REVIEW

**Comment by denzalman** [comment]
Looks like your buckets parsing works only with fixed buckets list range. Check it.

**Comment by hila3000** [comment]
@denzalman  Fixed, thanks :)

**Comment by denzalman** [comment]
looks better... nice work! :) 👍

**Comment by hila3000** [comment]
@L1nuxProdigy , please review and merge pull request. Thanks :)

**Pull request merged**
